# Change these first
owner: ZingLix # Your GitHub organization or username, where this repository lives
repo: blog-mirror-uptime # The name of this repository

sites:
  - name: zinglix.xyz
    url: https://zinglix.xyz
  - name: blog.zinglix.xyz
    url: https://blog.zinglix.xyz
  - name: cf.mirror.zinglix.xyz
    url: https://cf.mirror.zinglix.xyz
  - name: cf.ljnb.top
    url: https://cf.ljnb.top
  - name: zinglix-github-io.pages.dev
    url: https://zinglix-github-io.pages.dev
  - name: nf.ljnb.top
    url: https://nf.ljnb.top
  - name: laughing-mahavira-c38582.netlify.app
    url: https://laughing-mahavira-c38582.netlify.app
  - name: v.mirror.zinglix.xyz
    url: https://v.mirror.zinglix.xyz
  - name: v.ljnb.top
    url: https://v.ljnb.top
  - name: zing-lix-github-io.vercel.app
    url: https://zing-lix-github-io.vercel.app
  - name: gh.mirror.zinglix.xyz
    url: https://gh.mirror.zinglix.xyz
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: up.mirror.zinglix.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ZingLix Blog Mirror Uptime
  introTitle: "ZingLix Blog Mirror Uptime"
  introMessage: "[Mirrors Detail](https://zinglix.xyz/mirror)"
  navbar:
    - title: Status
      href: /
    - title: Detail
      href: https://zinglix.xyz/mirror
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
